import { readImportWorkbook } from "./xlsx-reader.js";
import { downloadPersonalisedTemplate, downloadSetupExport } from "./xlsx-writer.js";
const $=id=>document.getElementById(id); const fileInput=$("importFile"), status=$("importStatus"), preview=$("previewSection"), importButton=$("importButton"), serviceList=$("serviceList"), packageList=$("packageList"), summary=$("importSummary"), previewBody=$("previewBody"), templateBtn=$("downloadPersonalTemplate"), exportBtn=$("exportSetup");
let workbook=null, filename="", metadata=null;
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
function show(message,type="success"){status.hidden=false;status.className=`es-status ${type}`;status.textContent=message;} function hide(){status.hidden=true;}
function counts(){const names=["Customers","Bookings","Packages","Payments","Vouchers","Treatment Records"];return Object.fromEntries(names.map(name=>[name,(workbook?.[name]||[]).length]));}
function packageChoices(){const out=[];for(const t of metadata?.package_templates||[]){out.push({name:t.name,service:t.service_name});for(const v of (metadata?.package_variants||[]).filter(v=>v.package_template_id===t.id))out.push({name:`${t.name} · ${v.name}`,service:v.service_name||t.service_name});}return out;}
function matchText(sheet,row){if(!metadata)return "";if(sheet==="Bookings"||sheet==="Treatment Records"){const s=(metadata.services||[]).find(x=>x.name.toLowerCase()===String(row.service_name||"").trim().toLowerCase());return s?`Matched service: ${s.name}`:`Service not matched: ${row.service_name||"blank"}`;}if(sheet==="Packages"){const s=(metadata.services||[]).find(x=>x.name.toLowerCase()===String(row.service_name||"").trim().toLowerCase());const p=packageChoices().find(x=>x.name.toLowerCase()===String(row.package_name||"").trim().toLowerCase());return `${s?`Matched service: ${s.name}`:`Service not matched`}; ${p?`matched package: ${p.name}`:`package snapshot: ${row.package_name||"blank"}`}`;}return "";}
function render(){const c=counts();summary.innerHTML=Object.entries(c).map(([k,v])=>`<div><span>${esc(k)}</span><strong>${v}</strong></div>`).join("");const rows=[];for(const [sheet,data] of Object.entries(workbook||{})){if(!["Customers","Bookings","Packages","Payments","Vouchers","Treatment Records"].includes(sheet))continue;for(const row of data.slice(0,10))rows.push(`<tr><td>${esc(sheet)}</td><td>${esc(row.__row)}</td><td>${esc(row.external_customer_reference||row.external_booking_reference||row.external_package_reference||row.external_payment_reference||row.external_treatment_reference||row.code||"")}</td><td>${esc(row.first_name||row.service_name||row.package_name||row.payment_type||row.practitioner_name||row.name||"")}</td><td>${esc(matchText(sheet,row))}</td></tr>`);}previewBody.innerHTML=rows.join("")||`<tr><td colspan="5">No import rows found.</td></tr>`;preview.hidden=false;}
async function loadMetadata(){const r=await fetch("/api/import-data",{headers:{Accept:"application/json"},cache:"no-store"});if(r.status===401){location.href="/auth/login.html";return;}const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"Unable to load import settings.");metadata=d;serviceList.innerHTML=(d.services||[]).map(s=>`<span class="es-import-service-pill">${esc(s.name)}</span>`).join("")||`<span class="es-import-note">Create an active service before importing.</span>`;packageList.innerHTML=packageChoices().map(p=>`<span class="es-import-service-pill">${esc(p.name)}</span>`).join("")||`<span class="es-import-note">No active packages/courses yet.</span>`;templateBtn.disabled=false;exportBtn.disabled=false;}
templateBtn.addEventListener("click",()=>{if(metadata)downloadPersonalisedTemplate(metadata);}); exportBtn.addEventListener("click",()=>{if(metadata)downloadSetupExport(metadata);});
fileInput.addEventListener("change",async()=>{hide();preview.hidden=true;workbook=null;const file=fileInput.files?.[0];if(!file)return;if(file.size>15*1024*1024){show("Choose an Excel file smaller than 15 MB.","error");return;}try{workbook=await readImportWorkbook(file);filename=file.name;const c=counts(),total=Object.values(c).reduce((a,b)=>a+b,0);if(!total)throw new Error("The workbook has no import rows.");if(metadata&&total>Number(metadata.max_rows||500))throw new Error(`Import a maximum of ${metadata.max_rows||500} total rows at a time.`);render();show(`${total} data row${total===1?"":"s"} loaded. Check the matched service/package column before importing.`);}catch(e){show(e.message||"Unable to read this Excel file.","error");}});
importButton.addEventListener("click",async()=>{if(!workbook||importButton.disabled)return;const c=counts(),total=Object.values(c).reduce((a,b)=>a+b,0);if(!confirm(`Import ${total} rows? No booking confirmations, payment receipts or other historical emails will be sent.`))return;importButton.disabled=true;importButton.textContent="Importing…";hide();try{const r=await fetch("/api/import-data",{method:"POST",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify({filename,sheets:workbook})});if(r.status===401){location.href="/auth/login.html";return;}const d=await r.json();if(!r.ok||!d.ok){const detail=(d.errors||[]).slice(0,10).map(x=>`${x.sheet||"Row"} ${x.row}: ${x.message}`).join(" ");throw new Error(`${d.error||"Unable to import data."}${detail?` ${detail}`:""}`);}show(`Import complete: ${d.customers_imported} customers, ${d.bookings_imported} bookings, ${d.packages_imported} packages, ${d.payments_imported} payments, ${d.vouchers_imported} vouchers and ${d.treatment_records_imported||0} treatment records.`);workbook=null;fileInput.value="";preview.hidden=true;}catch(e){show(e.message||"Unable to import data.","error");}finally{importButton.disabled=false;importButton.textContent="Import data";}});
loadMetadata().catch(e=>show(e.message||"Unable to load import settings.","error"));
