import { readImportWorkbook } from "./xlsx-reader.js";
import { downloadPersonalisedTemplate } from "./xlsx-writer.js";
const $=id=>document.getElementById(id);
const fileInput=$("importFile"),status=$("importStatus"),preview=$("previewSection"),importButton=$("importButton"),serviceList=$("serviceList"),packageList=$("packageList"),summary=$("importSummary"),previewBody=$("previewBody"),templateBtn=$("downloadPersonalTemplate");
let workbook=null,filename="",metadata=null;
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
function show(message,type="success"){status.hidden=false;status.className=`es-status ${type}`;status.textContent=message;} function hide(){status.hidden=true;}
const names=["Customers","Bookings","Packages & Courses","Treatment History","Vouchers"];
function counts(){return Object.fromEntries(names.map(name=>[name,(workbook?.[name]||[]).length]));}
function packageChoices(){const out=[];for(const t of metadata?.package_templates||[]){out.push({name:t.name,service:t.service_name});for(const v of (metadata?.package_variants||[]).filter(v=>v.package_template_id===t.id))out.push({name:`${t.name} · ${v.name}`,service:v.service_name||t.service_name});}return out;}
function matchText(sheet,row){if(!metadata)return "";if(sheet==="Bookings"||sheet==="Treatment History"){const raw=String(row.eselram_service||"").trim();const s=(metadata.services||[]).find(x=>x.name.toLowerCase()===raw.toLowerCase());const pkg=String(row.package_or_course||"").trim();if(sheet==="Bookings"&&pkg){const p=packageChoices().find(x=>x.name.toLowerCase()===pkg.toLowerCase());return `${s?`Service: ${s.name}`:`Service not matched`}; ${p?`Package: ${p.name}`:`Package not matched`}`;}return s?`Service: ${s.name}`:`Service not matched: ${raw||"blank"}`;}if(sheet==="Packages & Courses"){const raw=String(row.eselram_package_or_course||"").trim();const p=packageChoices().find(x=>x.name.toLowerCase()===raw.toLowerCase());return p?`Package: ${p.name} · ${p.service}`:`Package not matched: ${raw||"blank"}`;}return "";}
function itemText(sheet,row){if(sheet==="Customers")return `${row.first_name||""} ${row.last_name||""}`.trim();if(sheet==="Bookings")return `${row.eselram_service||""} ${row.appointment_date||""} ${row.start_time||""}`.trim();if(sheet==="Packages & Courses"){const details=[];if(String(row.consultation_credit||"").trim())details.push(`consultation credit £${row.consultation_credit}`);if(String(row.discount||"").trim())details.push(`discount £${row.discount}`);if(String(row.amount_already_paid||"").trim())details.push(`paid £${row.amount_already_paid}`);return [row.eselram_package_or_course||"",details.join(" · ")].filter(Boolean).join(" · ");}if(sheet==="Treatment History")return `${row.eselram_service||""} ${row.treatment_date||""}`.trim();if(sheet==="Vouchers")return row.code||row.name||"";return "";}
function customerText(row){return row.customer_email_or_phone||row.email||row.phone||"";}
function render(){const c=counts();summary.innerHTML=Object.entries(c).map(([k,v])=>`<div><span>${esc(k)}</span><strong>${v}</strong></div>`).join("");const rows=[];for(const sheet of names){for(const row of (workbook?.[sheet]||[]).slice(0,10))rows.push(`<tr><td>${esc(sheet)}</td><td>${esc(row.__row)}</td><td>${esc(customerText(row))}</td><td>${esc(itemText(sheet,row))}</td><td>${esc(matchText(sheet,row))}</td></tr>`);}previewBody.innerHTML=rows.join("")||`<tr><td colspan="5">No import rows found.</td></tr>`;preview.hidden=false;}
async function loadMetadata(){const r=await fetch("/api/import-data",{headers:{Accept:"application/json"},cache:"no-store"});if(r.status===401){location.href="/auth/login.html";return;}const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||"Unable to load import settings.");metadata=d;serviceList.innerHTML=(d.services||[]).map(s=>`<span class="es-import-service-pill">${esc(s.name)}</span>`).join("")||`<span class="es-import-note">Create an active service before importing.</span>`;packageList.innerHTML=packageChoices().map(p=>`<span class="es-import-service-pill">${esc(p.name)}</span>`).join("")||`<span class="es-import-note">No active packages/courses yet.</span>`;templateBtn.disabled=false;}
templateBtn.addEventListener("click",()=>{if(metadata)downloadPersonalisedTemplate(metadata);});
fileInput.addEventListener("change",async()=>{hide();preview.hidden=true;workbook=null;const file=fileInput.files?.[0];if(!file)return;if(file.size>15*1024*1024){show("Choose an Excel file smaller than 15 MB.","error");return;}try{workbook=await readImportWorkbook(file);filename=file.name;const c=counts(),total=Object.values(c).reduce((a,b)=>a+b,0);if(!total)throw new Error("The workbook has no import rows.");if(metadata&&total>Number(metadata.max_rows||500))throw new Error(`Import a maximum of ${metadata.max_rows||500} total rows at a time.`);render();show(`${total} data row${total===1?"":"s"} loaded. Check the matches below before importing.`);}catch(e){show(e.message||"Unable to read this Excel file.","error");}});
importButton.addEventListener("click",async()=>{if(!workbook||importButton.disabled)return;const c=counts(),total=Object.values(c).reduce((a,b)=>a+b,0);if(!confirm(`Import ${total} rows? No Stripe charges/refunds or historical emails will be created.`))return;importButton.disabled=true;importButton.textContent="Importing…";hide();try{const r=await fetch("/api/import-data",{method:"POST",headers:{"Content-Type":"application/json",Accept:"application/json"},body:JSON.stringify({filename,sheets:workbook})});if(r.status===401){location.href="/auth/login.html";return;}const d=await r.json();if(!r.ok||!d.ok){const detail=(d.errors||[]).slice(0,12).map(x=>`${x.sheet||"Row"} ${x.row}: ${x.message}`).join(" ");throw new Error(`${d.error||"Unable to import data."}${detail?` ${detail}`:""}`);}show(`Import complete: ${d.customers_imported} customer rows, ${d.bookings_imported} bookings, ${d.packages_imported} packages/courses, ${d.payments_created} historical payments, ${d.vouchers_imported} vouchers and ${d.treatment_records_imported} treatment records.`);workbook=null;fileInput.value="";preview.hidden=true;}catch(e){show(e.message||"Unable to import data.","error");status.scrollIntoView({behavior:"smooth",block:"center"});}finally{importButton.disabled=false;importButton.textContent="Import data";}});
loadMetadata().catch(e=>show(e.message||"Unable to load import settings.","error"));
