const te = new TextEncoder();
const esc = value => String(value ?? "").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
function col(n){let s="";while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26);}return s;}
function crc32(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;}
function u16(n){return [n&255,(n>>>8)&255];} function u32(n){return [n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255];}
function zipStore(files){const parts=[],central=[];let offset=0;for(const f of files){const name=te.encode(f.name),data=typeof f.data==="string"?te.encode(f.data):f.data,crc=crc32(data);const local=new Uint8Array([...u32(0x04034b50),...u16(20),...u16(0),...u16(0),...u16(0),...u16(0),...u32(crc),...u32(data.length),...u32(data.length),...u16(name.length),...u16(0),...name]);parts.push(local,data);central.push(new Uint8Array([...u32(0x02014b50),...u16(20),...u16(20),...u16(0),...u16(0),...u16(0),...u16(0),...u32(crc),...u32(data.length),...u32(data.length),...u16(name.length),...u16(0),...u16(0),...u16(0),...u16(0),...u32(0),...u32(offset),...name]));offset+=local.length+data.length;}const centralOffset=offset,centralSize=central.reduce((n,p)=>n+p.length,0);const end=new Uint8Array([...u32(0x06054b50),...u16(0),...u16(0),...u16(files.length),...u16(files.length),...u32(centralSize),...u32(centralOffset),...u16(0)]);return new Blob([...parts,...central,end],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"});}
function cellXml(value,r,c,style=0){const ref=`${col(c)}${r}`;if(value===null||value===undefined||value==="")return `<c r="${ref}"${style?` s="${style}"`:""}/>`;if(typeof value==="number")return `<c r="${ref}"${style?` s="${style}"`:""}><v>${value}</v></c>`;return `<c r="${ref}" t="inlineStr"${style?` s="${style}"`:""}><is><t>${esc(value)}</t></is></c>`;}
function sheetXml(rows,{validations=[]}={}){const maxCols=Math.max(1,...rows.map(r=>r.length));let body="";rows.forEach((row,i)=>{const rn=i+1;body+=`<row r="${rn}">`+row.map((v,j)=>cellXml(v,rn,j+1,rn===1?1:0)).join("")+`</row>`;});const dvs=validations.length?`<dataValidations count="${validations.length}">${validations.map(v=>`<dataValidation type="list" allowBlank="1" showErrorMessage="1" sqref="${v.range}"><formula1>${esc(v.formula)}</formula1></dataValidation>`).join("")}</dataValidations>`:"";return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><dimension ref="A1:${col(maxCols)}${Math.max(rows.length,2)}"/><sheetViews><sheetView workbookViewId="0"/></sheetViews><sheetFormatPr defaultRowHeight="15"/><sheetData>${body}</sheetData>${dvs}</worksheet>`;}
const styles=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Aptos"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="11"/><name val="Aptos"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF365178"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="2"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1"/></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>`;
function makeWorkbook(sheets){const workbook=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${sheets.map((s,i)=>`<sheet name="${esc(s.name)}" sheetId="${i+1}" r:id="rId${i+1}"${s.hidden?' state="hidden"':''}/>`).join("")}</sheets></workbook>`;const rels=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${sheets.map((s,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join("")}<Relationship Id="rId${sheets.length+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`;const types=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>${sheets.map((s,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join("")}</Types>`;const rootrels=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`;const files=[{name:"[Content_Types].xml",data:types},{name:"_rels/.rels",data:rootrels},{name:"xl/workbook.xml",data:workbook},{name:"xl/_rels/workbook.xml.rels",data:rels},{name:"xl/styles.xml",data:styles}];sheets.forEach((s,i)=>files.push({name:`xl/worksheets/sheet${i+1}.xml`,data:sheetXml(s.rows,s)}));return zipStore(files);}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}

export function downloadPersonalisedTemplate(meta){
  const services=meta.services||[],templates=meta.package_templates||[],variants=meta.package_variants||[];
  const packageChoices=[];
  for(const t of templates){
    packageChoices.push({label:t.name,service:t.service_name||"",type:"Package",sessions:t.sessions_total,price:(Number(t.price_minor||0)/100).toFixed(2),id:t.id});
    for(const v of variants.filter(v=>v.package_template_id===t.id)) packageChoices.push({label:`${t.name} · ${v.name}`,service:v.service_name||t.service_name||"",type:"Variant",sessions:t.sessions_total,price:(Number(v.price_minor||0)/100).toFixed(2),id:v.id});
  }
  const setupRows=[["Type","Service","Service type","Package / course","Sessions","Price (£)"]];
  for(const s of services) setupRows.push(["Service",s.name,s.service_type,"","",(Number(s.price_minor||0)/100).toFixed(2)]);
  for(const p of packageChoices) setupRows.push([p.type,p.service,"",p.label,p.sessions,p.price]);
  const listRows=[["service","package_or_course"],...Array.from({length:Math.max(services.length,packageChoices.length,1)},(_,i)=>[services[i]?.name||"",packageChoices[i]?.label||""])];
  const serviceEnd=Math.max(2,services.length+1), packageEnd=Math.max(2,packageChoices.length+1);
  const sheets=[
    {name:"Instructions",rows:[
      ["Eselram import template","This workbook is personalised using this business's current Eselram services and packages."],
      ["Start with Customers","Enter each customer once. On the other sheets, identify them using the same email address, or phone number if they do not have an email."],
      ["Bookings","Choose an Eselram service from the dropdown. Leave Price blank to use the current Eselram service price. Amount already paid creates a historical manual payment record."],
      ["Packages & Courses","Choose the customer's Eselram package/course from the dropdown. Leave Package price blank to use the current Eselram price. If a paid completed consultation was credited to the package, enter that amount in Consultation credit (£). Completed bookings linked to that package count as used sessions."],
      ["Treatment History","Use this only if you want to preserve standard historical treatment-record details."],
      ["Vouchers","Optional. Use only when you want to bring voucher definitions into Eselram."],
      ["Dates","Use DD/MM/YYYY or YYYY-MM-DD. Times can be 18:30 or 6:30 pm."],
      ["Safety","Importing never charges/refunds Stripe and does not send historical booking/payment emails. Future reminders are off unless you choose Yes."],
      ["Limits","Maximum 500 data rows in one workbook and 15 MB per file."]
    ]},
    {name:"Customers",rows:[["First name","Last name","Email","Phone","Notes","Marketing consent"]],validations:[{range:"F2:F1000",formula:'"Yes,No"'}]},
    {name:"Bookings",rows:[["Customer email or phone","Eselram service","Appointment date","Start time","Status","Price (£)","Amount already paid (£)","Payment method","Discount (£)","Voucher used","Package or course","Send future reminder","Notes","Cancellation reason"]],validations:[{range:"B2:B1000",formula:`'Lists'!$A$2:$A$${serviceEnd}`},{range:"E2:E1000",formula:'"Confirmed,Completed,Cancelled,No show"'},{range:"K2:K1000",formula:`'Lists'!$B$2:$B$${packageEnd}`},{range:"L2:L1000",formula:'"Yes,No"'}]},
    {name:"Packages & Courses",rows:[["Customer email or phone","Eselram package or course","Status","Start date","Expiry date","Package price (£)","Consultation credit (£)","Amount already paid (£)","Payment method","Discount (£)","Voucher used","Notes"]],validations:[{range:"B2:B1000",formula:`'Lists'!$B$2:$B$${packageEnd}`},{range:"C2:C1000",formula:'"Active,Completed,Cancelled,Expired"'}]},
    {name:"Treatment History",rows:[["Customer email or phone","Eselram service","Treatment date","Status","Practitioner","Treatment area","Device","Device settings","Treatment notes","Client response","Client tolerance","Aftercare notes","Next session plan","Next treatment date"]],validations:[{range:"B2:B1000",formula:`'Lists'!$A$2:$A$${serviceEnd}`},{range:"D2:D1000",formula:'"Complete,Draft"'}]},
    {name:"Vouchers",rows:[["Code","Name","Discount type","Value","Active"]],validations:[{range:"C2:C1000",formula:'"Amount,Percent"'},{range:"E2:E1000",formula:'"Yes,No"'}]},
    {name:"Current Eselram Setup",rows:setupRows},
    {name:"Lists",rows:listRows,hidden:true}
  ];
  download(makeWorkbook(sheets),"eselram-import-template.xlsx");
}
