const te = new TextEncoder();
const esc = value => String(value ?? "").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
function col(n){let s="";while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26);}return s;}
function crc32(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;}
function u16(n){return [n&255,(n>>>8)&255];} function u32(n){return [n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255];}
function zipStore(files){const parts=[],central=[];let offset=0;for(const f of files){const name=te.encode(f.name),data=typeof f.data==="string"?te.encode(f.data):f.data,crc=crc32(data);const local=new Uint8Array([...u32(0x04034b50),...u16(20),...u16(0),...u16(0),...u16(0),...u16(0),...u32(crc),...u32(data.length),...u32(data.length),...u16(name.length),...u16(0),...name]);parts.push(local,data);central.push(new Uint8Array([...u32(0x02014b50),...u16(20),...u16(20),...u16(0),...u16(0),...u16(0),...u16(0),...u32(crc),...u32(data.length),...u32(data.length),...u16(name.length),...u16(0),...u16(0),...u16(0),...u16(0),...u32(0),...u32(offset),...name]));offset+=local.length+data.length;}const centralOffset=offset,centralSize=central.reduce((n,p)=>n+p.length,0);const end=new Uint8Array([...u32(0x06054b50),...u16(0),...u16(0),...u16(files.length),...u16(files.length),...u32(centralSize),...u32(centralOffset),...u16(0)]);return new Blob([...parts,...central,end],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"});}
function cellXml(value,r,c,style=0){const ref=`${col(c)}${r}`;if(value===null||value===undefined||value==="")return `<c r="${ref}"${style?` s="${style}"`:""}/>`;if(typeof value==="number")return `<c r="${ref}"${style?` s="${style}"`:""}><v>${value}</v></c>`;return `<c r="${ref}" t="inlineStr"${style?` s="${style}"`:""}><is><t>${esc(value)}</t></is></c>`;}
function sheetXml(rows,{validations=[],hidden=false}={}){const maxCols=Math.max(1,...rows.map(r=>r.length));let body="";rows.forEach((row,i)=>{const rn=i+1;body+=`<row r="${rn}">`+row.map((v,j)=>cellXml(v,rn,j+1,rn===1?1:0)).join("")+`</row>`;});const dvs=validations.length?`<dataValidations count="${validations.length}">${validations.map(v=>`<dataValidation type="list" allowBlank="1" showErrorMessage="1" sqref="${v.range}"><formula1>${esc(v.formula)}</formula1></dataValidation>`).join("")}</dataValidations>`:"";return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><dimension ref="A1:${col(maxCols)}${Math.max(rows.length,2)}"/><sheetViews><sheetView workbookViewId="0"/></sheetViews><sheetFormatPr defaultRowHeight="15"/><sheetData>${body}</sheetData>${dvs}</worksheet>`;}
const styles=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Aptos"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="11"/><name val="Aptos"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF365178"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="2"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1"/></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>`;
function makeWorkbook(sheets){const workbook=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${sheets.map((s,i)=>`<sheet name="${esc(s.name)}" sheetId="${i+1}" r:id="rId${i+1}"${s.hidden?' state="hidden"':''}/>`).join("")}</sheets></workbook>`;const rels=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${sheets.map((s,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join("")}<Relationship Id="rId${sheets.length+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`;const types=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>${sheets.map((s,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join("")}</Types>`;const rootrels=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`;const files=[{name:"[Content_Types].xml",data:types},{name:"_rels/.rels",data:rootrels},{name:"xl/workbook.xml",data:workbook},{name:"xl/_rels/workbook.xml.rels",data:rels},{name:"xl/styles.xml",data:styles}];sheets.forEach((s,i)=>files.push({name:`xl/worksheets/sheet${i+1}.xml`,data:sheetXml(s.rows,s)}));return zipStore(files);}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function downloadPersonalisedTemplate(meta){const services=meta.services||[],templates=meta.package_templates||[],variants=meta.package_variants||[];const serviceNames=services.map(x=>x.name);const packageChoices=[];for(const t of templates){packageChoices.push({label:t.name,service:t.service_name||"",kind:"Template",sessions:t.sessions_total,price:(Number(t.price_minor||0)/100).toFixed(2),id:t.id});for(const v of variants.filter(v=>v.package_template_id===t.id))packageChoices.push({label:`${t.name} · ${v.name}`,service:v.service_name||t.service_name||"",kind:"Variant",sessions:t.sessions_total,price:(Number(v.price_minor||0)/100).toFixed(2),id:v.id});}
 const refRows=[["service_name","service_id","service_type","duration_minutes","price_gbp"],...services.map(s=>[s.name,s.id,s.service_type,s.duration_minutes,(Number(s.price_minor||0)/100).toFixed(2)]),[],["package_name","package_id","type","service_name","sessions_total","price_gbp"],...packageChoices.map(p=>[p.label,p.id,p.kind,p.service,p.sessions,p.price])];
 const serviceEnd=Math.max(2,services.length+1),pkgStart=services.length+4,pkgEnd=Math.max(pkgStart+1,pkgStart+packageChoices.length);
 const sheets=[
 {name:"Instructions",rows:[["Eselram personalised import template","Generated from this business's current Eselram setup."],["Service names","Choose from the dropdown. The list comes directly from active Eselram services."],["Package names","Choose from the dropdown. The list comes directly from current package templates and variants."],["External references","Use IDs from the previous booking app to link rows and prevent duplicates."],["Safety","Imported payments are historical/manual; importing never creates Stripe charges or historical emails."]]},
 {name:"Customers",rows:[["external_customer_reference","first_name","last_name","email","phone","notes","marketing_consent"]]},
 {name:"Bookings",rows:[["external_booking_reference","external_customer_reference","email","phone","service_name","appointment_date","start_time","status","duration_minutes","price_gbp","discount_gbp","voucher_code","deposit_due_gbp","customer_notes","internal_notes","reminders","package_external_reference","cancellation_reason"]],validations:[{range:"E2:E1000",formula:`'Setup Reference'!$A$2:$A$${serviceEnd}`},{range:"H2:H1000",formula:'"confirmed,completed,cancelled,no_show"'},{range:"P2:P1000",formula:'"yes,no"'}]},
 {name:"Packages",rows:[["external_package_reference","external_customer_reference","email","phone","service_name","package_name","sessions_total","status","starts_on","expires_on","price_gbp","discount_gbp","voucher_code","notes"]],validations:[{range:"E2:E1000",formula:`'Setup Reference'!$A$2:$A$${serviceEnd}`},{range:"F2:F1000",formula:`'Setup Reference'!$A$${pkgStart+1}:$A$${pkgEnd}`},{range:"H2:H1000",formula:'"active,completed,cancelled,expired"'}]},
 {name:"Payments",rows:[["external_payment_reference","external_customer_reference","email","phone","booking_external_reference","package_external_reference","payment_type","amount_gbp","status","payment_method","paid_at","provider_reference","notes"]],validations:[{range:"G2:G1000",formula:'"full,deposit,balance,pay_at_appointment,refund"'},{range:"I2:I1000",formula:'"pending,paid,due,failed,refunded,partially_refunded"'}]},
 {name:"Vouchers",rows:[["code","name","discount_type","value","is_active"]],validations:[{range:"C2:C1000",formula:'"amount,percent"'},{range:"E2:E1000",formula:'"yes,no"'}]},
 {name:"Treatment Records",rows:[["external_treatment_reference","external_customer_reference","email","phone","external_booking_reference","service_name","status","treatment_date","practitioner_name","treatment_area","device_name","device_settings","treatment_notes","client_response","client_tolerance","aftercare_notes","next_session_plan","next_treatment_date"]],validations:[{range:"F2:F1000",formula:`'Setup Reference'!$A$2:$A$${serviceEnd}`},{range:"G2:G1000",formula:'"draft,complete"'}]},
 {name:"Setup Reference",rows:refRows,hidden:true}
 ];download(makeWorkbook(sheets),"eselram-personalised-data-import.xlsx");}
export function downloadSetupExport(meta){const rows=[["Type","Service name","Service ID","Service type","Package / variant","Package ID","Sessions","Price","Active"]];for(const s of meta.services||[])rows.push(["Service",s.name,s.id,s.service_type,"","","",(Number(s.price_minor||0)/100).toFixed(2),s.is_active?"Yes":"No"]);for(const t of meta.package_templates||[])rows.push(["Package",t.service_name,t.service_id,"",t.name,t.id,t.sessions_total,(Number(t.price_minor||0)/100).toFixed(2),t.is_active?"Yes":"No"]);for(const v of meta.package_variants||[])rows.push(["Package variant",v.service_name,v.service_id,"",`${v.template_name} · ${v.name}`,v.id,v.sessions_total,(Number(v.price_minor||0)/100).toFixed(2),v.is_active?"Yes":"No"]);download(makeWorkbook([{name:"Current Eselram Setup",rows}]),"eselram-current-setup.xlsx");}
