import { readSessionToken, hashSessionToken } from "../../../lib/auth.js";

const MAX_ROWS = 500;
const BOOKING_STATUSES = new Set(["confirmed","completed","cancelled","no_show"]);
const PACKAGE_STATUSES = new Set(["active","completed","cancelled","expired"]);
const PAYMENT_STATUSES = new Set(["pending","paid","due","failed","refunded","partially_refunded"]);
const TREATMENT_STATUSES = new Set(["draft","complete"]);
const PAYMENT_TYPES = new Set(["full","deposit","balance","pay_at_appointment","refund"]);

async function getUserContext(request, env) {
  const token = readSessionToken(request); if (!token) return null;
  const tokenHash = await hashSessionToken(token);
  return env.DB.prepare(`SELECT u.id AS user_id,u.business_id,b.currency FROM user_sessions s JOIN users u ON u.id=s.user_id JOIN businesses b ON b.id=u.business_id WHERE s.token_hash=? AND s.revoked_at IS NULL AND datetime(s.expires_at)>datetime('now') AND u.is_active=1 LIMIT 1`).bind(tokenHash).first();
}
const unauthorized=()=>Response.json({ok:false,error:"Authentication required."},{status:401});
const clean=(v,max=500)=>String(v??"").trim().slice(0,max);
const ref=v=>clean(v,180);
const key=v=>ref(v).toLowerCase();
function cleanEmail(v){const e=clean(v,254).toLowerCase();if(!e)return"";return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e)?e:null;}
const phone=v=>clean(v,80);
function yesNo(v,f=false){const t=clean(v,20).toLowerCase();if(!t)return f;return ["yes","y","true","1","on"].includes(t);}
function excelDate(v){const n=Number(v);if(!Number.isFinite(n))return null;const d=new Date(Date.UTC(1899,11,30)+Math.round(n*86400000));return Number.isNaN(d.getTime())?null:d.toISOString().slice(0,10);}
function dateOnly(v){const t=clean(v,50);if(!t)return null;if(/^\d+(?:\.\d+)?$/.test(t))return excelDate(t);if(/^\d{4}-\d{2}-\d{2}$/.test(t))return t;const m=t.match(/^(\d{1,2})[\/.-](\d{1,2})[\/.-](\d{4})$/);return m?`${m[3]}-${m[2].padStart(2,"0")}-${m[1].padStart(2,"0")}`:null;}
function timeOnly(v){const t=clean(v,50);if(!t)return null;if(/^\d+(?:\.\d+)?$/.test(t)){const f=((Number(t)%1)+1)%1,total=Math.round(f*1440)%1440;return`${String(Math.floor(total/60)).padStart(2,"0")}:${String(total%60).padStart(2,"0")}`;}const m=t.match(/^(\d{1,2}):(\d{2})(?::\d{2})?\s*(am|pm)?$/i);if(!m)return null;let h=Number(m[1]);const min=Number(m[2]);if(min>59)return null;if(m[3]){if(h<1||h>12)return null;if(m[3].toLowerCase()==="pm"&&h!==12)h+=12;if(m[3].toLowerCase()==="am"&&h===12)h=0;}if(h>23)return null;return`${String(h).padStart(2,"0")}:${String(min).padStart(2,"0")}`;}
function dateTime(v){const t=clean(v,80);if(!t)return null;if(/^\d+(?:\.\d+)?$/.test(t)){const n=Number(t),epoch=Date.UTC(1899,11,30),d=new Date(epoch+Math.round(n*86400000));return Number.isNaN(d.getTime())?null:d.toISOString().slice(0,19);}const iso=t.match(/^(\d{4}-\d{2}-\d{2})(?:[ T](\d{1,2}:\d{2})(?::\d{2})?)?$/);if(iso){const tm=iso[2]?timeOnly(iso[2]):"12:00";return tm?`${iso[1]}T${tm}:00`:null;}const d=dateOnly(t);return d?`${d}T12:00:00`:null;}
function money(v,fallback=null){const t=clean(v,40).replace(/[£,$\s]/g,"");if(!t)return fallback;const n=Number(t);return Number.isFinite(n)&&n>=0?Math.round(n*100):null;}
function addMinutes(date,time,mins){const d=new Date(`${date}T${time}:00Z`);return Number.isNaN(d.getTime())?null:new Date(d.getTime()+mins*60000).toISOString().slice(0,19);}
function noteWithDiscount(notes, discountMinor, voucher){const parts=[clean(notes,3000)];if(discountMinor>0)parts.push(`Imported discount £${(discountMinor/100).toFixed(2)}${voucher?` · voucher ${voucher}`:""}`);return parts.filter(Boolean).join(" · ")||null;}
function err(errors,sheet,row,field,message){errors.push({sheet,row,field,message});}

export async function onRequestGet({request,env}){
  const user=await getUserContext(request,env);if(!user)return unauthorized();
  const [services, templates, variants] = await Promise.all([
    env.DB.prepare(`SELECT id,name,duration_minutes,price_minor,service_type,is_active FROM services WHERE business_id=? AND is_active=1 ORDER BY sort_order,name COLLATE NOCASE`).bind(user.business_id).all(),
    env.DB.prepare(`SELECT pt.id,pt.service_id,pt.name,pt.sessions_total,pt.price_minor,pt.deposit_minor,pt.is_active,s.name AS service_name FROM package_templates pt JOIN services s ON s.id=pt.service_id AND s.business_id=pt.business_id WHERE pt.business_id=? AND pt.is_active=1 ORDER BY pt.name COLLATE NOCASE`).bind(user.business_id).all(),
    env.DB.prepare(`SELECT pv.id,pv.package_template_id,pv.service_id,pv.name,pv.price_minor,pv.deposit_minor,pv.is_active,pt.name AS template_name,pt.sessions_total,s.name AS service_name FROM package_variants pv JOIN package_templates pt ON pt.id=pv.package_template_id AND pt.business_id=pv.business_id JOIN services s ON s.id=pv.service_id AND s.business_id=pv.business_id WHERE pv.business_id=? AND pv.is_active=1 AND pt.is_active=1 ORDER BY pt.name COLLATE NOCASE,pv.sort_order,pv.name COLLATE NOCASE`).bind(user.business_id).all()
  ]);
  return Response.json({ok:true,max_rows:MAX_ROWS,services:services.results||[],package_templates:templates.results||[],package_variants:variants.results||[]});
}

export async function onRequestPost({request,env}){
 try{
  const user=await getUserContext(request,env);if(!user)return unauthorized();
  const body=await request.json().catch(()=>({})), sheets=body.sheets&&typeof body.sheets==="object"?body.sheets:{}, filename=clean(body.filename,255)||"eselram-data-import.xlsx";
  const rows={Customers:Array.isArray(sheets.Customers)?sheets.Customers:[],Bookings:Array.isArray(sheets.Bookings)?sheets.Bookings:[],Packages:Array.isArray(sheets.Packages)?sheets.Packages:[],Payments:Array.isArray(sheets.Payments)?sheets.Payments:[],Vouchers:Array.isArray(sheets.Vouchers)?sheets.Vouchers:[],TreatmentRecords:Array.isArray(sheets["Treatment Records"])?sheets["Treatment Records"]:[]};
  const total=Object.values(rows).reduce((n,a)=>n+a.length,0);if(!total)return Response.json({ok:false,error:"No import rows were supplied."},{status:400});if(total>MAX_ROWS)return Response.json({ok:false,error:`Import a maximum of ${MAX_ROWS} total rows at a time.`},{status:400});

  const [serviceRes,customerRes,refRes,voucherSetting,templateRes,variantRes,existingPackageRes,existingBookingRes]=await Promise.all([
    env.DB.prepare(`SELECT id,name,duration_minutes,price_minor,service_type FROM services WHERE business_id=? AND is_active=1`).bind(user.business_id).all(),
    env.DB.prepare(`SELECT id,first_name,last_name,email,phone FROM customers WHERE business_id=?`).bind(user.business_id).all(),
    env.DB.prepare(`SELECT entity_type,external_reference,internal_id FROM data_import_references WHERE business_id=?`).bind(user.business_id).all(),
    env.DB.prepare(`SELECT setting_value FROM business_settings WHERE business_id=? AND setting_key='payment_vouchers' LIMIT 1`).bind(user.business_id).first(),
    env.DB.prepare(`SELECT id,service_id,name FROM package_templates WHERE business_id=?`).bind(user.business_id).all(),
    env.DB.prepare(`SELECT id,package_template_id,service_id,name FROM package_variants WHERE business_id=?`).bind(user.business_id).all(),
    env.DB.prepare(`SELECT id,customer_id,service_id FROM customer_packages WHERE business_id=?`).bind(user.business_id).all(),
    env.DB.prepare(`SELECT id,customer_id,service_id FROM appointments WHERE business_id=?`).bind(user.business_id).all()
  ]);
  const services=new Map((serviceRes.results||[]).map(s=>[String(s.name).trim().toLowerCase(),s]));
  const packageTemplates=templateRes.results||[], packageVariants=variantRes.results||[]; const existingPackagesById=new Map((existingPackageRes.results||[]).map(x=>[x.id,x])); const existingBookingsById=new Map((existingBookingRes.results||[]).map(x=>[x.id,x]));
  const customersByEmail=new Map(),customersByPhone=new Map();for(const c of customerRes.results||[]){if(c.email)customersByEmail.set(String(c.email).toLowerCase(),c);if(c.phone)customersByPhone.set(String(c.phone).replace(/\s+/g,""),c);}
  const existingRefs=new Map((refRes.results||[]).map(r=>[`${r.entity_type}:${key(r.external_reference)}`,r.internal_id]));
  let currentVouchers=[];try{currentVouchers=JSON.parse(voucherSetting?.setting_value||"[]");if(!Array.isArray(currentVouchers))currentVouchers=[];}catch{currentVouchers=[];}
  const errors=[], statements=[], batchId=`imp_${crypto.randomUUID()}`;const customerRefMap=new Map(),packageRefMap=new Map(),bookingRefMap=new Map(),seenPaymentRefs=new Set();let customersCreated=0;

  // Customers: create or map first so all other sheets can reference them.
  for(const input of rows.Customers){const rn=Number(input.__row||0), external=ref(input.external_customer_reference), first=clean(input.first_name,100), last=clean(input.last_name,100), email=cleanEmail(input.email), ph=phone(input.phone);
    if(!first)err(errors,"Customers",rn,"first_name","First name is required.");if(!last)err(errors,"Customers",rn,"last_name","Last name is required.");if(email===null)err(errors,"Customers",rn,"email","Email address is invalid.");
    if(external&&customerRefMap.has(key(external)))err(errors,"Customers",rn,"external_customer_reference","Customer reference is duplicated in this workbook.");
    let customer=null;if(external&&existingRefs.has(`customer:${key(external)}`)){const id=existingRefs.get(`customer:${key(external)}`);customer=(customerRes.results||[]).find(c=>c.id===id)||{id};}
    if(!customer&&email)customer=customersByEmail.get(email);if(!customer&&ph)customer=customersByPhone.get(ph.replace(/\s+/g,""));
    if(!customer&&first&&last&&email!==null){const id=`cus_${crypto.randomUUID()}`;customer={id,first_name:first,last_name:last,email:email||null,phone:ph||null};customersCreated++;statements.push(env.DB.prepare(`INSERT INTO customers(id,business_id,first_name,last_name,email,phone,notes,marketing_consent) VALUES(?,?,?,?,?,?,?,?)`).bind(id,user.business_id,first,last,email||null,ph||null,clean(input.notes,4000)||null,yesNo(input.marketing_consent,false)?1:0));if(email)customersByEmail.set(email,customer);if(ph)customersByPhone.set(ph.replace(/\s+/g,""),customer);}
    if(customer&&external){customerRefMap.set(key(external),customer.id);if(!existingRefs.has(`customer:${key(external)}`))statements.push(env.DB.prepare(`INSERT INTO data_import_references(business_id,import_batch_id,entity_type,external_reference,internal_id) VALUES(?,?,?,?,?)`).bind(user.business_id,batchId,"customer",external,customer.id));}
  }

  function resolveCustomer(input,sheet,rn){const external=ref(input.external_customer_reference),email=cleanEmail(input.email),ph=phone(input.phone);if(email===null){err(errors,sheet,rn,"email","Email address is invalid.");return null;}let id=null;if(external)id=customerRefMap.get(key(external))||existingRefs.get(`customer:${key(external)}`)||null;if(!id&&email)id=customersByEmail.get(email)?.id||null;if(!id&&ph)id=customersByPhone.get(ph.replace(/\s+/g,""))?.id||null;if(!id)err(errors,sheet,rn,"external_customer_reference","Customer could not be matched. Add the customer to the Customers sheet or provide an existing email/phone.");return id;}

  // Packages are created before bookings so booking rows can link to them.
  for(const input of rows.Packages){const rn=Number(input.__row||0), external=ref(input.external_package_reference), customerId=resolveCustomer(input,"Packages",rn), serviceName=clean(input.service_name,200), service=services.get(serviceName.toLowerCase()), name=clean(input.package_name,200), totalSessions=Number(input.sessions_total), status=clean(input.status,30).toLowerCase(), starts=dateOnly(input.starts_on), expires=clean(input.expires_on)?dateOnly(input.expires_on):null, price=money(input.price_gbp,0), discount=money(input.discount_gbp,0), voucher=clean(input.voucher_code,80).toUpperCase();
    if(!external)err(errors,"Packages",rn,"external_package_reference","Package reference is required so bookings/payments can link to it safely.");else if(packageRefMap.has(key(external))||existingRefs.has(`package:${key(external)}`))err(errors,"Packages",rn,"external_package_reference","Package reference already exists or is duplicated.");if(!service)err(errors,"Packages",rn,"service_name",`Service '${serviceName||"(blank)"}' does not match an active Eselram service.`);if(!name)err(errors,"Packages",rn,"package_name","Package name is required.");if(!Number.isInteger(totalSessions)||totalSessions<1||totalSessions>999)err(errors,"Packages",rn,"sessions_total","Sessions total must be between 1 and 999.");if(!PACKAGE_STATUSES.has(status))err(errors,"Packages",rn,"status","Status must be active, completed, cancelled or expired.");if(clean(input.starts_on)&&!starts)err(errors,"Packages",rn,"starts_on","Start date is invalid.");if(clean(input.expires_on)&&!expires)err(errors,"Packages",rn,"expires_on","Expiry date is invalid.");if(price===null||discount===null||discount>price)err(errors,"Packages",rn,"price_gbp","Price/discount amounts are invalid.");
    if(customerId&&service&&external&&name&&Number.isInteger(totalSessions)&&PACKAGE_STATUSES.has(status)&&price!==null&&discount!==null&&discount<=price){const id=`cpk_${crypto.randomUUID()}`,finalPrice=Math.max(price-discount,0); const exactVariant=packageVariants.find(v=>{const t=packageTemplates.find(x=>x.id===v.package_template_id);const variantName=String(v.name||"").trim().toLowerCase();const fullName=t?`${String(t.name||"").trim()} · ${String(v.name||"").trim()}`.toLowerCase():variantName;return v.service_id===service.id&&(variantName===name.toLowerCase()||fullName===name.toLowerCase());}); const exactTemplate=exactVariant?packageTemplates.find(t=>t.id===exactVariant.package_template_id):packageTemplates.find(t=>t.service_id===service.id&&String(t.name||"").trim().toLowerCase()===name.toLowerCase()); packageRefMap.set(key(external),{id,serviceId:service.id,customerId});statements.push(env.DB.prepare(`INSERT INTO customer_packages(id,business_id,customer_id,package_template_id,service_id,name_snapshot,sessions_total,price_minor,status,starts_on,expires_on,notes,package_variant_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,user.business_id,customerId,exactTemplate?.id||null,service.id,name,totalSessions,finalPrice,status,starts,expires,noteWithDiscount(input.notes,discount,voucher),exactVariant?.id||null));statements.push(env.DB.prepare(`INSERT INTO data_import_references(business_id,import_batch_id,entity_type,external_reference,internal_id) VALUES(?,?,?,?,?)`).bind(user.business_id,batchId,"package",external,id));}
  }

  for(const input of rows.Bookings){const rn=Number(input.__row||0), external=ref(input.external_booking_reference), customerId=resolveCustomer(input,"Bookings",rn), serviceName=clean(input.service_name,200), service=services.get(serviceName.toLowerCase()), date=dateOnly(input.appointment_date), time=timeOnly(input.start_time), status=clean(input.status,30).toLowerCase().replaceAll(" ","_"), duration=clean(input.duration_minutes,20)?Number(input.duration_minutes):Number(service?.duration_minutes||0), price=money(input.price_gbp,service?Number(service.price_minor||0):0), discount=money(input.discount_gbp,0), deposit=money(input.deposit_due_gbp,0), packageExternal=ref(input.package_external_reference), voucher=clean(input.voucher_code,80).toUpperCase();
    if(!external)err(errors,"Bookings",rn,"external_booking_reference","Booking reference is required to prevent duplicate migration.");else if(bookingRefMap.has(key(external))||existingRefs.has(`booking:${key(external)}`))err(errors,"Bookings",rn,"external_booking_reference","Booking reference already exists or is duplicated.");if(!service)err(errors,"Bookings",rn,"service_name",`Service '${serviceName||"(blank)"}' does not match an active Eselram service.`);if(!date)err(errors,"Bookings",rn,"appointment_date","Appointment date is invalid.");if(!time)err(errors,"Bookings",rn,"start_time","Start time is invalid.");if(!BOOKING_STATUSES.has(status))err(errors,"Bookings",rn,"status","Status must be confirmed, completed, cancelled or no_show.");if(!Number.isInteger(duration)||duration<1||duration>1440)err(errors,"Bookings",rn,"duration_minutes","Duration must be between 1 and 1440 minutes.");if(price===null||discount===null||discount>price||deposit===null)err(errors,"Bookings",rn,"price_gbp","Price, discount or deposit amount is invalid.");let pkg=null;if(packageExternal){pkg=packageRefMap.get(key(packageExternal));if(!pkg&&existingRefs.has(`package:${key(packageExternal)}`)){const eid=existingRefs.get(`package:${key(packageExternal)}`);const ep=existingPackagesById.get(eid);pkg={id:eid,serviceId:ep?.service_id,customerId:ep?.customer_id};}if(!pkg)err(errors,"Bookings",rn,"package_external_reference","Linked package reference was not found.");if(pkg?.serviceId&&service&&pkg.serviceId!==service.id)err(errors,"Bookings",rn,"package_external_reference","Booking service does not match the linked package service.");if(pkg?.customerId&&customerId&&pkg.customerId!==customerId)err(errors,"Bookings",rn,"package_external_reference","Booking customer does not match the linked package customer.");}
    if(customerId&&service&&external&&date&&time&&BOOKING_STATUSES.has(status)&&Number.isInteger(duration)&&duration>0&&price!==null&&discount!==null&&discount<=price&&deposit!==null){const id=`apt_${crypto.randomUUID()}`,start=`${date}T${time}:00`,end=addMinutes(date,time,duration),finalPrice=pkg?.id?0:Math.max(price-discount,0),kind=service.service_type==="consultation"?"consultation":"service";bookingRefMap.set(key(external),{id,customerId});statements.push(env.DB.prepare(`INSERT INTO appointments(id,business_id,customer_id,service_id,status,start_at,end_at,price_minor,deposit_due_minor,booking_source,booking_kind,customer_notes,internal_notes,cancelled_at,cancellation_reason,import_batch_id,external_reference,reminders_enabled) VALUES(?,?,?,?,?,?,?,?,?,'import',?,?,?,CASE WHEN ?='cancelled' THEN CURRENT_TIMESTAMP ELSE NULL END,?,?,?,?)`).bind(id,user.business_id,customerId,service.id,status,start,end,finalPrice,pkg?.id?0:Math.min(deposit,finalPrice),kind,clean(input.customer_notes,3000)||null,noteWithDiscount(input.internal_notes,discount,voucher),status,clean(input.cancellation_reason,500)||null,batchId,external,yesNo(input.reminders,false)?1:0));statements.push(env.DB.prepare(`INSERT INTO data_import_references(business_id,import_batch_id,entity_type,external_reference,internal_id) VALUES(?,?,?,?,?)`).bind(user.business_id,batchId,"booking",external,id));if(pkg?.id)statements.push(env.DB.prepare(`INSERT INTO customer_package_appointments(customer_package_id,appointment_id) VALUES(?,?)`).bind(pkg.id,id));}
  }

  for(const input of rows.Payments){const rn=Number(input.__row||0), external=ref(input.external_payment_reference), customerId=resolveCustomer(input,"Payments",rn), bookingExternal=ref(input.booking_external_reference), packageExternal=ref(input.package_external_reference), type=clean(input.payment_type,40).toLowerCase(), status=clean(input.status,40).toLowerCase(), amount=money(input.amount_gbp,null), paidAt=clean(input.paid_at)?dateTime(input.paid_at):null, method=clean(input.payment_method,80)||"imported", providerReference=clean(input.provider_reference,180)||external||null;
    if(!external)err(errors,"Payments",rn,"external_payment_reference","Payment reference is required to prevent duplicates.");else if(existingRefs.has(`payment:${key(external)}`)||seenPaymentRefs.has(key(external)))err(errors,"Payments",rn,"external_payment_reference","Payment reference has already been imported or is duplicated in this workbook.");if(external)seenPaymentRefs.add(key(external));if(!PAYMENT_TYPES.has(type))err(errors,"Payments",rn,"payment_type","Payment type must be full, deposit, balance, pay_at_appointment or refund.");if(!PAYMENT_STATUSES.has(status))err(errors,"Payments",rn,"status","Payment status is invalid.");if(amount===null)err(errors,"Payments",rn,"amount_gbp","Payment amount is invalid.");if(clean(input.paid_at)&&!paidAt)err(errors,"Payments",rn,"paid_at","Paid date/time is invalid.");let booking=null,pkg=null;if(bookingExternal){booking=bookingRefMap.get(key(bookingExternal));if(!booking&&existingRefs.has(`booking:${key(bookingExternal)}`)){const eid=existingRefs.get(`booking:${key(bookingExternal)}`);const eb=existingBookingsById.get(eid);booking={id:eid,customerId:eb?.customer_id,serviceId:eb?.service_id};}if(!booking)err(errors,"Payments",rn,"booking_external_reference","Linked booking was not found.");}if(packageExternal){pkg=packageRefMap.get(key(packageExternal));if(!pkg&&existingRefs.has(`package:${key(packageExternal)}`)){const eid=existingRefs.get(`package:${key(packageExternal)}`);const ep=existingPackagesById.get(eid);pkg={id:eid,serviceId:ep?.service_id,customerId:ep?.customer_id};}if(!pkg)err(errors,"Payments",rn,"package_external_reference","Linked package was not found.");}if(booking?.customerId&&booking.customerId!==customerId)err(errors,"Payments",rn,"booking_external_reference","Payment customer does not match the linked booking customer.");if(pkg?.customerId&&pkg.customerId!==customerId)err(errors,"Payments",rn,"package_external_reference","Payment customer does not match the linked package customer.");if(!booking&&!pkg)err(errors,"Payments",rn,"booking_external_reference","Link the historical payment to a booking or package.");
    if(customerId&&external&&PAYMENT_TYPES.has(type)&&PAYMENT_STATUSES.has(status)&&amount!==null&&(booking||pkg)){const id=`pay_${crypto.randomUUID()}`;const effectivePaidAt=paidAt||(status==="paid"||status==="refunded"||status==="partially_refunded"?new Date().toISOString().slice(0,19):null);statements.push(env.DB.prepare(`INSERT INTO payments(id,business_id,appointment_id,customer_id,provider,payment_type,amount_minor,currency,status,provider_reference,paid_at,payment_method,notes) VALUES(?,?,?,?, 'manual', ?,?,?,?,?,?,?,?)`).bind(id,user.business_id,booking?.id||null,customerId,type,amount,String(user.currency||"GBP").toUpperCase(),status,providerReference,effectivePaidAt,method,clean(input.notes,3000)||"Imported historical payment"));statements.push(env.DB.prepare(`INSERT INTO data_import_references(business_id,import_batch_id,entity_type,external_reference,internal_id) VALUES(?,?,?,?,?)`).bind(user.business_id,batchId,"payment",external,id));if(pkg?.id)statements.push(env.DB.prepare(`INSERT INTO customer_package_payments(customer_package_id,payment_id) VALUES(?,?)`).bind(pkg.id,id));}
  }

  // Optional historical treatment records use Eselram's existing treatment_records structure.
  const seenTreatmentRefs=new Set();
  for(const input of rows.TreatmentRecords){const rn=Number(input.__row||0), external=ref(input.external_treatment_reference), customerId=resolveCustomer(input,"Treatment Records",rn), bookingExternal=ref(input.external_booking_reference), serviceName=clean(input.service_name,200), service=services.get(serviceName.toLowerCase()), status=clean(input.status,30).toLowerCase()||"complete", treatmentDate=dateOnly(input.treatment_date), nextDate=clean(input.next_treatment_date)?dateOnly(input.next_treatment_date):null;
    if(!external)err(errors,"Treatment Records",rn,"external_treatment_reference","Treatment reference is required to prevent duplicates.");else if(existingRefs.has(`treatment_record:${key(external)}`)||seenTreatmentRefs.has(key(external)))err(errors,"Treatment Records",rn,"external_treatment_reference","Treatment reference already exists or is duplicated.");if(external)seenTreatmentRefs.add(key(external));if(!service)err(errors,"Treatment Records",rn,"service_name",`Service '${serviceName||"(blank)"}' does not match an active Eselram service.`);if(!TREATMENT_STATUSES.has(status))err(errors,"Treatment Records",rn,"status","Status must be draft or complete.");if(!treatmentDate)err(errors,"Treatment Records",rn,"treatment_date","Treatment date is invalid.");if(clean(input.next_treatment_date)&&!nextDate)err(errors,"Treatment Records",rn,"next_treatment_date","Next treatment date is invalid.");let booking=null;if(bookingExternal){booking=bookingRefMap.get(key(bookingExternal));if(!booking&&existingRefs.has(`booking:${key(bookingExternal)}`)){const eid=existingRefs.get(`booking:${key(bookingExternal)}`);const eb=existingBookingsById.get(eid);booking={id:eid,customerId:eb?.customer_id,serviceId:eb?.service_id};}if(!booking)err(errors,"Treatment Records",rn,"external_booking_reference","Linked booking was not found.");if(booking?.customerId&&booking.customerId!==customerId)err(errors,"Treatment Records",rn,"external_booking_reference","Treatment customer does not match the linked booking customer.");if(booking?.serviceId&&service&&booking.serviceId!==service.id)err(errors,"Treatment Records",rn,"external_booking_reference","Treatment service does not match the linked booking service.");}
    if(customerId&&service&&external&&TREATMENT_STATUSES.has(status)&&treatmentDate){const id=`tr_${crypto.randomUUID()}`;statements.push(env.DB.prepare(`INSERT INTO treatment_records(id,business_id,appointment_id,customer_id,service_id,status,treatment_date,practitioner_name,treatment_area,device_name,device_settings,treatment_notes,client_response,client_tolerance,aftercare_notes,next_session_plan,next_treatment_date,import_batch_id,external_reference) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,user.business_id,booking?.id||null,customerId,service.id,status,treatmentDate,clean(input.practitioner_name,200)||null,clean(input.treatment_area,500)||null,clean(input.device_name,300)||null,clean(input.device_settings,3000)||null,clean(input.treatment_notes,5000)||null,clean(input.client_response,3000)||null,clean(input.client_tolerance,1000)||null,clean(input.aftercare_notes,3000)||null,clean(input.next_session_plan,3000)||null,nextDate,batchId,external));statements.push(env.DB.prepare(`INSERT INTO data_import_references(business_id,import_batch_id,entity_type,external_reference,internal_id) VALUES(?,?,?,?,?)`).bind(user.business_id,batchId,"treatment_record",external,id));}
  }

  // Vouchers are business configuration, merged without overwriting existing codes.
  const voucherCodes=new Set(currentVouchers.map(v=>String(v.code||"").trim().toUpperCase()));const importedVouchers=[];
  for(const input of rows.Vouchers){const rn=Number(input.__row||0), code=clean(input.code,80).toUpperCase().replace(/\s+/g,""), name=clean(input.name,80)||code, type=clean(input.discount_type,30).toLowerCase(), value=Number(String(input.value??"").replace(/[£,%,$\s]/g,"")), active=yesNo(input.is_active,true);if(!code)err(errors,"Vouchers",rn,"code","Voucher code is required.");if(!["amount","percent"].includes(type))err(errors,"Vouchers",rn,"discount_type","Discount type must be amount or percent.");if(!Number.isFinite(value)||value<=0||(type==="percent"&&value>100))err(errors,"Vouchers",rn,"value","Voucher value is invalid.");if(voucherCodes.has(code))err(errors,"Vouchers",rn,"code",`Voucher code ${code} already exists or is duplicated.`);if(code&&["amount","percent"].includes(type)&&Number.isFinite(value)&&value>0&&(type!=="percent"||value<=100)){voucherCodes.add(code);importedVouchers.push({id:`vch_${crypto.randomUUID()}`,code,name,discount_type:type,value,is_active:active});}}

  if(errors.length)return Response.json({ok:false,error:"Nothing was imported. Fix the workbook errors and try again.",errors},{status:400});
  statements.unshift(env.DB.prepare(`INSERT INTO data_import_batches(id,business_id,created_by_user_id,source_filename,customers_imported,bookings_imported,packages_imported,payments_imported,vouchers_imported,treatment_records_imported) VALUES(?,?,?,?,?,?,?,?,?,?)`).bind(batchId,user.business_id,user.user_id,filename,rows.Customers.length,rows.Bookings.length,rows.Packages.length,rows.Payments.length,rows.Vouchers.length,rows.TreatmentRecords.length));
  if(importedVouchers.length){const merged=[...currentVouchers,...importedVouchers];statements.push(env.DB.prepare(`INSERT INTO business_settings(id,business_id,setting_key,setting_value,value_type) VALUES(?,?,'payment_vouchers',?,'json') ON CONFLICT(business_id,setting_key) DO UPDATE SET setting_value=excluded.setting_value,value_type='json',updated_at=CURRENT_TIMESTAMP`).bind(`set_${crypto.randomUUID()}`,user.business_id,JSON.stringify(merged)));}
  await env.DB.batch(statements);
  return Response.json({ok:true,batch_id:batchId,customers_imported:rows.Customers.length,customers_created:customersCreated,bookings_imported:rows.Bookings.length,packages_imported:rows.Packages.length,payments_imported:rows.Payments.length,vouchers_imported:rows.Vouchers.length,treatment_records_imported:rows.TreatmentRecords.length});
 }catch(error){console.error("Data import failed:",error);return Response.json({ok:false,error:"Unable to import data. Nothing was intentionally sent to Stripe or email providers."},{status:500});}
}
